### ISSUE TITLE
Change `detectcore` function for cluster computation

### ISSUE THREAD

**Issue by yufree** [MASHUOA/HiTMaP#11]
Hi, I wonder if you could change the core detection function from `detectcore()` to `future::availableCores()` as the former function will return all the core number on the cluster node instead of the request core numbers(see details [here](https://www.jottr.org/2022/12/05/avoid-detectcores/)). Meanwhile, the `BiocParallel` function will also use `detectcore()` for default settings. Thanks.

**Comment by MASHUOA** [comment]
Thanks for reminding me. The code has been modified accordingly.
