### ISSUE TITLE
Clustering imaging issue

### ISSUE THREAD

**Issue by xiweifan** [MASHUOA/HiTMaP#3]
Hi George,

Hope you are doing well!

I feel there is something that needs to be rectified to generate a clustering image. 

Here is the code you used for clustering image: (https://github.com/MASHUOA/HiTMaP/tree/1.0.1)

library(magick)
p_cluster1<-image_read(paste0(wd,"/Summary folder/cluster Ion images/791_cluster_imaging.png"))
print(p_cluster1)

## 1 PNG     1980   1308 sRGB       TRUE    302087 118x118

I think it should be:
p_cluster1<-image_read(paste0(wd,"/Summary folder/cluster Ion images/unique/791_cluster_imaging.png"))

Moreover, I can not generate an image like this:
![image](https://user-images.githubusercontent.com/87630521/131272532-58ddb954-a1ad-4853-800e-888bcfd4c7b2.png)

But the pictures like this:

![34554_cluster_imaging](https://user-images.githubusercontent.com/87630521/131272564-b3add2c1-22e7-47e4-94b8-e9aa3a6865eb.png)

I am wondering if there is anything wrong with my code?

Thanks,
Xiwei

**Comment by MASHUOA** [comment]
Hi, Xiwei
Sorry for my slow reply. 
Sure, may I confirm whether you are running the same script with example data and your data in the same environment?
orca package mentioned in the tutorial .md file is the module that generates this table. If the error exists, you may need to configure the orca library in your singularity image to make sure it's working properly.
Another possible reason will be the cluster image rendering function cannot find the candidate_list object.
You can set export_Header_table=TRUE to make sure this procedure will be executed.
Let me know if there's an error message.
Best,
George
