### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by GraceAHall** [MASHUOA/HiTMaP#5]
Hi there, 

Attempting to wrap HiT-MaP so it can be available on the Galaxy platform.
Running into a number of issues during execution using your provided docker image. Here is the second:

```
Ranking mz feature: 50 unique candidates mz, 50 aligned mz feature
Start protein scoring...
Error in Protein_feature_result[[3]] : subscript out of bounds
Calls: imaging_identification -> IMS_data_process
```

I believe what is occuring is that Protein_feature_result is expected to have an array with multiple elements, but it gets none. 
Unfortunately this halts execution (after 1.5 hours of processing). 

Would be good to catch this type of error and handle it, rather than cause the program to terminate. 
Maybe it is possible to check Protein_feature_result has the required data before trying to access specific elements which may or may not be present?

**Comment by MASHUOA** [comment]
Hi, Grace,
I found it's mz range upper boundary cause this error. 
You need to update the hitmap via installation code (for unknown reason Cardinal package won't read the data according to a given mz.range) and set "mzrange = c(1220,1624)" in the argument.
here's an example code:


**datafile=c("mouse_kidney_cut.imzML")
wd="~/expdata/kindney/"
library(HiTMaP)
imaging_identification(datafile=paste0(wd,datafile),Digestion_site="trypsin",threshold = 0,
                       Fastadatabase="uniprot_mouse_20210107.fasta",output_candidatelist=T,
                      preprocess=list(force_preprocess=T,
                               use_preprocessRDS=TRUE,
                               smoothSignal=list(method="gaussian"),
                               reduceBaseline=list(method="locmin"),
                               peakPick=list(method="adaptive"),
                               peakAlign=list(tolerance=25,level="global", units="ppm"),
                               normalize=list(method="rms")),
                       spectra_segments_per_file=5,use_previous_candidates=T,ppm=25,FDR_cutoff = 0.05,IMS_analysis=T,Thread=1,
                       Rotate_IMG=NULL,cluster_rds_path="/combinedimdata.rds",
                       mzrange = c(1220,1624),plot_cluster_image_grid=T,pixel_size_um = 150,remove_score_outlier=F,attach_summary_cluster = F, remove_cluster_from_grid=F,plot_cluster_image_overwrite=T)**

**Comment by MASHUOA** [comment]
HI, Grace,
Thanks for your comments.
Now the issue has been fixed in the latest update.
