### ISSUE TITLE
Error during PCA

### ISSUE THREAD

**Issue by philippa1812** [MASHUOA/HiTMaP#7]
Hi, I am trying to use your workflow on my data using the Docker image mashuoa/hitmap:natcomms but it gets stuck during PCA:
```
Segmentation in progress...
projecting 12 principal components...
  |                                                                      |   0%Error in if (dists[cand] == 0) return(c(NA, NA)) : 
  argument is of length zero
```
Any suggestions how to fix this?

**Comment by MASHUOA** [comment]
Hello, there
Can you please provide more info for debugging?
I can see that docker configurations may differ and some containers may not be able to perform the analysis with allocated RAM.
