### ISSUE TITLE
Error in Example workflow （Mouse brain）

### ISSUE THREAD

**Issue by pangkun97** [MASHUOA/HiTMaP#8]
![image](https://github.com/MASHUOA/HiTMaP/assets/47656551/f3474513-0545-4976-8ccf-fb7587a52658)

**Comment by MASHUOA** [comment]
Hello,
The example file requires 32GB minimum RAM for 2-thread processing in a Windows system. The thread can't share the image file so each thread will consume around 12 GB of RAM. If the error persists, please try to use a single-thread workflow.

**Comment by MASHUOA** [comment]
Hi, There,
I have gone through the workflow again, the normalization process will create a big object (100 times of the original data).
I'm contacting the author for a bug fix. Before that please disable the normalization procedure by setting:
normalize=list(method="Disable")
